name: ADK Q&A Agent

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  agent-answer-questions:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-adk

      - name: Run Q&A Script
        env:
          GITHUB_TOKEN: ${{ secrets.ADK_TRIAGE_AGENT }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_CLOUD_LOCATION: ${{ secrets.GOOGLE_CLOUD_LOCATION }}
          VERTEXAI_DATASTORE_ID: ${{ secrets.VERTEXAI_DATASTORE_ID }}
          GOOGLE_GENAI_USE_VERTEXAI: 1
          OWNER: 'xuanyang15'
          REPO: 'adk-python'
          INTERACTIVE: 0
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          PYTHONPATH: contributing/samples
        run: python -m adk_repo_answering_agent.main
